name: analytics_futebol
version: "1.0.0"
config-version: 2

profile: analytics_futebol

model-paths: ["models"]
test-paths: ["tests"]

models:
  analytics_futebol:          # <-- chave do projeto dentro de models (permitido)
    staging:
      +materialized: view
    marts:
      +materialized: table