name: pipeline-futebol
on:
  schedule:
    - cron: "41 16 * * *"   # todo dia 07:00
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: sudo apt-get update && sudo apt-get install -y libpq-dev
      - run: pip install -r requirements.txt
      - run: python -c "import psycopg2, psycopg2.extensions; print(psycopg2.__version__, psycopg2.extensions.libpq_version())"
      # - run: python -c "import os; print('FOOTBALL_API_TOKEN=', os.environ.get('FOOTBALL_API_TOKEN'))"
      #   env:
      #     FOOTBALL_API_TOKEN: ${{ secrets.FOOTBALL_API_TOKEN }}
      - run: python run_pipeline.py
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_DATABASE: dbanalytics
          DBT_PROFILES_DIR: ${{ github.workspace }}
          FOOTBALL_API_TOKEN: ${{ secrets.FOOTBALL_API_TOKEN }}
